name: drawer_menu
description: Aplicación de peces.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  font_awesome_flutter: ^8.5.0
  validators: ^2.0.0
  firebase_auth: ^0.15.2
  cloud_firestore: ^0.13.0+1
  provider: ^3.2.0
  google_sign_in: ^4.4.0
  flutter_facebook_login: ^3.0.0  
  flutter_hide_show_password_input: ^0.0.1  
  flutter_spinkit: "^4.1.2"
  rflutter_alert: ^1.0.3
  image_picker: ^0.6.5
  firebase_storage: ^3.1.5
  flutter_launcher_icons: "^0.7.3"
  flappy_search_bar: ^1.7.2
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.4.3
  intl: ^0.16.1
  pdf: ^1.7.1
  open_file: ^3.0.1
  path_provider: ^1.6.7



  fluttertoast: ^7.0.4
  cached_network_image: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons: ^0.7.4

flutter_icons:
  image_path: "assets/images/Pez.png"
  android: "launcher_icon"
  ios: true
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/Pez.png
    - assets/images/p.jpg
    - assets/images/fish-loading.gif